import matplotlib.pyplot as plt
import matplotlib.colors as cls
import numpy as np
import argparse

str1 = "This script epot per atom of all the structures in the input file."
parser = argparse.ArgumentParser(description=str1)
parser.add_argument('inpDiffdat', action='store' ,type=str, help="input file")
parser.add_argument('outPng', action='store' ,type=str, help="output png file")
args=parser.parse_args()

inpData=open(args.inpDiffdat,'r')
diri=[]
dirj=[]
iati=[]
iatj=[]
ACSFD=[]
OMFPD=[]
EtotD=[]
EHD=[]
ExcD=[]
EvxcD=[]
EionD=[]
EBSD=[]
QatD=[]



for iline,line in enumerate(inpData):
    if iline==0:
        continue
    diri.append(line.split()[0])
    dirj.append(line.split()[1])
    iati.append(line.split()[2])
    iatj.append(line.split()[3])
    ACSFD.append(float(line.split()[4]))
    OMFPD.append(float(line.split()[5]))
    EtotD.append(float(line.split()[6]))
    EHD.append(float(line.split()[7]))
    ExcD.append(float(line.split()[8]))
    EvxcD.append(float(line.split()[9]))
    EionD.append(float(line.split()[10]))
    EBSD.append(float(line.split()[11]))
    QatD.append(float(line.split()[12]))

ACSFD=np.divide(ACSFD,np.max(ACSFD))
OMFPD=np.divide(OMFPD,np.max(OMFPD))
ZoomBound=1.E-2
######Getting Zoom Values##########
AZlist=np.where(ACSFD<ZoomBound)
ACSFDAZ=[]
EtotDAZ=[]
EHDAZ=[]
ExcDAZ=[]
EvxcDAZ=[]
EionDAZ=[]
EBSDAZ=[]
QatDAZ=[]
for i in AZlist[0]:
    print(i)
    ACSFDAZ.append(ACSFD[i])
    EtotDAZ.append(EtotD[i])
    EHDAZ.append(EHD[i])
    ExcDAZ.append( ExcD[i])
    EvxcDAZ.append(EvxcD[i])
    EionDAZ.append(EionD[i])
    EBSDAZ.append( EBSD[i])
    QatDAZ.append( QatD[i])
OZlist=np.where(OMFPD<ZoomBound)
OMFPDOZ=[]
EtotDOZ=[]
EHDOZ=[]
ExcDOZ=[]
EvxcDOZ=[]
EionDOZ=[]
EBSDOZ=[]
QatDOZ=[]
for i in OZlist[0]:
    OMFPDOZ.append(OMFPD[i])
    EtotDOZ.append(EtotD[i])
    EHDOZ.append(  EHD[i])
    ExcDOZ.append( ExcD[i])
    EvxcDOZ.append(EvxcD[i])
    EionDOZ.append(EionD[i])
    EBSDOZ.append( EBSD[i])
    QatDOZ.append( QatD[i])

mxEtot=max(EtotD)
coeff = 1.01
mxEtot *= coeff
mxEH=max(EHD)
mxEH *= coeff
mxExc=max(ExcD)
mxExc *= coeff
mxEvxc=max(EvxcD)
mxEvxc *= coeff
mxEion=max(EionD)
mxEion *= coeff
mxEBS=max(EBSD)
mxEBS *= coeff
mxQat=max(QatD)
mxQat *= coeff

#print(binsNum)

xlimVal=1.0
binsNum=int(len(EtotD)/500)
binsNumZoom=int(len(EtotD)/5000)
msSize=2.0
cMap='jet'
############HIST2D################################################################
fig,axs=plt.subplots(4,4,figsize=(20,20))
fig.tight_layout(pad=5.0)
#axs[0,0].set_title('EBS+EXC-EvXC-EH')
gs=axs[0,0].get_gridspec()
for ax in axs[0,0:2]:
    ax.remove()
axbig = fig.add_subplot(gs[0,0:2])
#axbig.plot(ACSFD,EtotD,'.r')
#_,_,_,im00=axbig.hist2d(ACSFD, EtotD, cmap=cMap, bins=binsNum, norm=cls.PowerNorm(gamma=0.2))
_,_,_,im00=axbig.hist2d(ACSFD, EtotD, cmap=cMap, bins=binsNum, norm=cls.LogNorm())
fig.colorbar(im00,ax=axbig)
axbig.set(xlabel='ACSF differance',ylabel='E Diff')
axbig.set_xlim(0.0,xlimVal)
axbig.set_ylim(0.0,mxEtot)
#axs[1,0].set_title('EH')
#axs[1,0].plot(ACSFD,EHD,'.g')
_,_,_,im01=axs[1,0].hist2d(ACSFD, EHD, cmap=cMap, bins=binsNum, norm=cls.LogNorm())
fig.colorbar(im01,ax=axs[1,0])
axs[1,0].set(xlabel='ACSF differance',ylabel='EH Diff')
axs[1,0].set_xlim(0.0,xlimVal)
axs[1,0].set_ylim(0.0,mxEH)
#axs[1,1].set_title('EBS')
#axs[1,1].plot(ACSFD,EBSD,'.b')
_,_,_,im02=axs[1,1].hist2d(ACSFD, EBSD, cmap=cMap, bins=binsNum, norm=cls.LogNorm())
fig.colorbar(im02,ax=axs[1,1])
axs[1,1].set(xlabel='ACSF differance',ylabel='EBS Diff')
axs[1,1].set_xlim(0.0,xlimVal)
axs[1,1].set_ylim(0.0,mxEBS)
#axs[2,0].set_title('EXC')
#axs[2,0].plot(ACSFD,ExcD,'.c')
_,_,_,im03=axs[2,0].hist2d(ACSFD, ExcD, cmap=cMap, bins=binsNum, norm=cls.LogNorm())
fig.colorbar(im03,ax=axs[2,0])
axs[2,0].set(xlabel='ACSF differance',ylabel='EXC Diff')
axs[2,0].set_xlim(0.0,xlimVal)
axs[2,0].set_ylim(0.0,mxExc)
#axs[2,1].set_title('EVXC')
#axs[2,1].plot(ACSFD,EvxcD,'.y')
_,_,_,im04=axs[2,1].hist2d(ACSFD, EvxcD, cmap=cMap, bins=binsNum, norm=cls.LogNorm())
fig.colorbar(im04,ax=axs[2,1])
axs[2,1].set(xlabel='ACSF differance',ylabel='EVXC Diff')
axs[2,1].set_xlim(0.0,xlimVal)
axs[2,1].set_ylim(0.0,mxEvxc)
#axs[3,0].set_title('Eion')
#axs[3,0].plot(ACSFD,EionD,'.m')
_,_,_,im05=axs[3,0].hist2d(ACSFD, EionD, cmap=cMap, bins=binsNum, norm=cls.LogNorm())
fig.colorbar(im05,ax=axs[3,0])
axs[3,0].set(xlabel='ACSF differance',ylabel='Eion Diff')
axs[3,0].set_xlim(0.0,xlimVal)
axs[3,0].set_ylim(0.0,mxEion)
#axs[3,1].set_title('Eion')
#axs[3,1].plot(ACSFD,QatD,'.k')
_,_,_,im06=axs[3,1].hist2d(ACSFD, QatD, cmap=cMap, bins=binsNum, norm=cls.LogNorm())
fig.colorbar(im06,ax=axs[3,1])
axs[3,1].set(xlabel='ACSF differance',ylabel='Qat Diff')
axs[3,1].set_xlim(0.0,xlimVal)
axs[3,1].set_ylim(0.0,mxQat)
#axs[0,2].set_title('EBS+EXC-EvXC-EH')
gs=axs[0,2].get_gridspec()
for ax in axs[0,2:]:
    ax.remove()
axbig2 = fig.add_subplot(gs[0,2:])
#axbig.plot(OMFPD,EtotD,'.r',markersize=0.1)
_,_,_,im07=axbig2.hist2d(OMFPD, EtotD, cmap=cMap, bins=binsNum, norm=cls.LogNorm())
fig.colorbar(im07,ax=axbig2)
axbig2.set(xlabel='OMFP differance',ylabel='E Diff')
axbig2.set_xlim(0.0,xlimVal)
axbig2.set_ylim(0.0,mxEtot)
#axs[1,2].set_title('EH')
#axs[1,2].plot(OMFPD,EHD,'.g')
_,_,_,im08=axs[1,2].hist2d(OMFPD, EHD, cmap=cMap, bins=binsNum, norm=cls.LogNorm())
fig.colorbar(im08,ax=axs[1,2])
axs[1,2].set(xlabel='OMFP differance',ylabel='EH Diff')
axs[1,2].set_xlim(0.0,xlimVal)
axs[1,2].set_ylim(0.0,mxEH)
#axs[1,3].set_title('EBS')
#axs[1,3].plot(OMFPD,EBSD,'.b')
_,_,_,im09=axs[1,3].hist2d(OMFPD, EBSD, cmap=cMap, bins=binsNum, norm=cls.LogNorm())
fig.colorbar(im09,ax=axs[1,3])
axs[1,3].set(xlabel='OMFP differance',ylabel='EBS Diff')
axs[1,3].set_xlim(0.0,xlimVal)
axs[1,3].set_ylim(0.0,mxEBS)
#axs[2,2].set_title('EXC')
#axs[2,2].plot(OMFPD,ExcD,'.c')
_,_,_,im10=axs[2,2].hist2d(OMFPD, ExcD, cmap=cMap, bins=binsNum, norm=cls.LogNorm())
fig.colorbar(im10,ax=axs[2,2])
axs[2,2].set(xlabel='OMFP differance',ylabel='EXC Diff')
axs[2,2].set_ylim(0.0,mxExc)
axs[2,2].set_xlim(0.0,xlimVal)
#axs[2,2].set_title('EVXC')
#axs[2,3].plot(OMFPD,EvxcD,'.y')
_,_,_,im11=axs[2,3].hist2d(OMFPD, EvxcD, cmap=cMap, bins=binsNum, norm=cls.LogNorm())
fig.colorbar(im11,ax=axs[2,3])
axs[2,3].set(xlabel='OMFP differance',ylabel='EVXC Diff')
axs[2,3].set_xlim(0.0,xlimVal)
axs[2,3].set_ylim(0.0,mxEvxc)
#axs[3,2].set_title('Eion')
#axs[3,2].plot(OMFPD,EionD,'.m')
_,_,_,im12=axs[3,2].hist2d(OMFPD, EionD, cmap=cMap, bins=binsNum, norm=cls.LogNorm())
fig.colorbar(im12,ax=axs[3,2])
axs[3,2].set(xlabel='OMFP differance',ylabel='Eion Diff')
axs[3,2].set_ylim(0.0,mxEion)
axs[3,2].set_xlim(0.0,xlimVal)
#axs[3,3].set_title('Eion')
#axs[3,3].plot(OMFPD,QatD,'.k')
_,_,_,im13=axs[3,3].hist2d(OMFPD, QatD, cmap=cMap, bins=binsNum, norm=cls.LogNorm())
fig.colorbar(im13,ax=axs[3,3])
axs[3,3].set(xlabel='OMFP differance',ylabel='Qat Diff')
axs[3,3].set_xlim(0.0,xlimVal)
axs[3,3].set_ylim(0.0,mxQat)
#plt.show()
fig.savefig('hist_'+args.outPng,dpi=200)
fig.clf()
del fig
print('Have a nice day!')
############HIST2D################################################################
############Normal################################################################
fig,axs=plt.subplots(4,4,figsize=(20,20))
fig.tight_layout(pad=5.0)
#axs[0,0].set_title('EBS+EXC-EvXC-EH')
gs=axs[0,0].get_gridspec()
for ax in axs[0,0:2]:
    ax.remove()
axbig = fig.add_subplot(gs[0,0:2])
axbig.plot(ACSFD,EtotD,',r',)
axbig.set(xlabel='ACSF differance',ylabel='E Diff')
axbig.set_xlim(0.0,xlimVal)
axbig.set_ylim(0.0,mxEtot)
#axs[1,0].set_title('EH')
axs[1,0].plot(ACSFD,EHD,',g')
axs[1,0].set(xlabel='ACSF differance',ylabel='EH Diff')
axs[1,0].set_xlim(0.0,xlimVal)
axs[1,0].set_ylim(0.0,mxEH)
#axs[1,1].set_title('EBS')
axs[1,1].plot(ACSFD,EBSD,',b')
axs[1,1].set(xlabel='ACSF differance',ylabel='EBS Diff')
axs[1,1].set_xlim(0.0,xlimVal)
axs[1,1].set_ylim(0.0,mxEBS)
#axs[2,0].set_title('EXC')
axs[2,0].plot(ACSFD,ExcD,',c')
axs[2,0].set(xlabel='ACSF differance',ylabel='EXC Diff')
axs[2,0].set_xlim(0.0,xlimVal)
axs[2,0].set_ylim(0.0,mxExc)
#axs[2,1].set_title('EVXC')
axs[2,1].plot(ACSFD,EvxcD,',y')
axs[2,1].set(xlabel='ACSF differance',ylabel='EVXC Diff')
axs[2,1].set_xlim(0.0,xlimVal)
axs[2,1].set_ylim(0.0,mxEvxc)
#axs[3,0].set_title('Eion')
axs[3,0].plot(ACSFD,EionD,',m')
axs[3,0].set(xlabel='ACSF differance',ylabel='Eion Diff')
axs[3,0].set_xlim(0.0,xlimVal)
axs[3,0].set_ylim(0.0,mxEion)
#axs[3,1].set_title('Eion')
axs[3,1].plot(ACSFD,QatD,',k')
axs[3,1].set(xlabel='ACSF differance',ylabel='Qat Diff')
axs[3,1].set_xlim(0.0,xlimVal)
axs[3,1].set_ylim(0.0,mxQat)
#axs[0,2].set_title('EBS+EXC-EvXC-EH')
gs=axs[0,2].get_gridspec()
for ax in axs[0,2:]:
    ax.remove()
axbig2 = fig.add_subplot(gs[0,2:])
axbig2.plot(OMFPD,EtotD,',r',markersize=0.1)
axbig2.set(xlabel='OMFP differance',ylabel='E Diff')
axbig2.set_xlim(0.0,xlimVal)
axbig2.set_ylim(0.0,mxEtot)
#axs[1,2].set_title('EH')
axs[1,2].plot(OMFPD,EHD,',g')
axs[1,2].set(xlabel='OMFP differance',ylabel='EH Diff')
axs[1,2].set_xlim(0.0,xlimVal)
axs[1,2].set_ylim(0.0,mxEH)
#axs[1,3].set_title('EBS')
axs[1,3].plot(OMFPD,EBSD,',b')
axs[1,3].set(xlabel='OMFP differance',ylabel='EBS Diff')
axs[1,3].set_xlim(0.0,xlimVal)
axs[1,3].set_ylim(0.0,mxEBS)
#axs[2,2].set_title('EXC')
axs[2,2].plot(OMFPD,ExcD,',c')
axs[2,2].set(xlabel='OMFP differance',ylabel='EXC Diff')
axs[2,2].set_ylim(0.0,mxExc)
axs[2,2].set_xlim(0.0,xlimVal)
#axs[2,2].set_title('EVXC')
axs[2,3].plot(OMFPD,EvxcD,',y')
axs[2,3].set(xlabel='OMFP differance',ylabel='EVXC Diff')
axs[2,3].set_xlim(0.0,xlimVal)
axs[2,3].set_ylim(0.0,mxEvxc)
#axs[3,2].set_title('Eion')
axs[3,2].plot(OMFPD,EionD,',m')
axs[3,2].set(xlabel='OMFP differance',ylabel='Eion Diff')
axs[3,2].set_ylim(0.0,mxEion)
axs[3,2].set_xlim(0.0,xlimVal)
#axs[3,3].set_title('Eion')
axs[3,3].plot(OMFPD,QatD,',k')
axs[3,3].set(xlabel='OMFP differance',ylabel='Qat Diff')
axs[3,3].set_xlim(0.0,xlimVal)
axs[3,3].set_ylim(0.0,mxQat)
#plt.show()
fig.savefig('norm_'+args.outPng,dpi=200)
fig.clf()
del fig
print('Have a nice day!')
############Normal################################################################
############HIST2DZOOM################################################################
fig,axs=plt.subplots(4,4,figsize=(20,20))
fig.tight_layout(pad=5.0)
#axs[0,0].set_title('EBS+EXC-EvXC-EH')
gs=axs[0,0].get_gridspec()
for ax in axs[0,0:2]:
    ax.remove()
axbig = fig.add_subplot(gs[0,0:2])
#axbig.plot(ACSFD,EtotD,'.r')
#_,_,_,im00=axbig.hist2d(ACSFD, EtotD, cmap=cMap, bins=binsNum, norm=cls.PowerNorm(gamma=0.2))
_,_,_,im00=axbig.hist2d(ACSFDAZ, EtotDAZ, cmap=cMap, bins=binsNumZoom, norm=cls.LogNorm())
fig.colorbar(im00,ax=axbig)
axbig.set(xlabel='ACSF differance',ylabel='E Diff')
axbig.set_xlim(0.0,ZoomBound)
#axs[1,0].set_title('EH')
#axs[1,0].plot(ACSFD,EHD,'.g')
_,_,_,im01=axs[1,0].hist2d(ACSFDAZ, EHDAZ, cmap=cMap, bins=binsNumZoom, norm=cls.LogNorm())
fig.colorbar(im01,ax=axs[1,0])
axs[1,0].set(xlabel='ACSF differance',ylabel='EH Diff')
axs[1,0].set_xlim(0.0,ZoomBound)
#axs[1,1].set_title('EBS')
#axs[1,1].plot(ACSFD,EBSD,'.b')
_,_,_,im02=axs[1,1].hist2d(ACSFDAZ, EBSDAZ, cmap=cMap, bins=binsNumZoom, norm=cls.LogNorm())
fig.colorbar(im02,ax=axs[1,1])
axs[1,1].set(xlabel='ACSF differance',ylabel='EBS Diff')
axs[1,1].set_xlim(0.0,ZoomBound)
#axs[2,0].set_title('EXC')
#axs[2,0].plot(ACSFD,ExcD,'.c')
_,_,_,im03=axs[2,0].hist2d(ACSFDAZ, ExcDAZ, cmap=cMap, bins=binsNumZoom, norm=cls.LogNorm())
fig.colorbar(im03,ax=axs[2,0])
axs[2,0].set(xlabel='ACSF differance',ylabel='EXC Diff')
axs[2,0].set_xlim(0.0,ZoomBound)
#axs[2,1].set_title('EVXC')
#axs[2,1].plot(ACSFD,EvxcD,'.y')
_,_,_,im04=axs[2,1].hist2d(ACSFDAZ, EvxcDAZ, cmap=cMap, bins=binsNumZoom, norm=cls.LogNorm())
fig.colorbar(im04,ax=axs[2,1])
axs[2,1].set(xlabel='ACSF differance',ylabel='EVXC Diff')
axs[2,1].set_xlim(0.0,ZoomBound)
#axs[3,0].set_title('Eion')
#axs[3,0].plot(ACSFD,EionD,'.m')
_,_,_,im05=axs[3,0].hist2d(ACSFDAZ, EionDAZ, cmap=cMap, bins=binsNumZoom, norm=cls.LogNorm())
fig.colorbar(im05,ax=axs[3,0])
axs[3,0].set(xlabel='ACSF differance',ylabel='Eion Diff')
axs[3,0].set_xlim(0.0,ZoomBound)
#axs[3,1].set_title('Eion')
#axs[3,1].plot(ACSFD,QatD,'.k')
_,_,_,im06=axs[3,1].hist2d(ACSFDAZ, QatDAZ, cmap=cMap, bins=binsNumZoom, norm=cls.LogNorm())
fig.colorbar(im06,ax=axs[3,1])
axs[3,1].set(xlabel='ACSF differance',ylabel='Qat Diff')
axs[3,1].set_xlim(0.0,ZoomBound)
#axs[0,2].set_title('EBS+EXC-EvXC-EH')
gs=axs[0,2].get_gridspec()
for ax in axs[0,2:]:
    ax.remove()
axbig2 = fig.add_subplot(gs[0,2:])
#axbig.plot(OMFPD,EtotD,'.r',markersize=0.1)
_,_,_,im07=axbig2.hist2d(OMFPDOZ, EtotDOZ, cmap=cMap, bins=binsNumZoom, norm=cls.LogNorm())
fig.colorbar(im07,ax=axbig2)
axbig2.set(xlabel='OMFP differance',ylabel='E Diff')
axbig2.set_xlim(0.0,ZoomBound)
#axs[1,2].set_title('EH')
#axs[1,2].plot(OMFPD,EHD,'.g')
_,_,_,im08=axs[1,2].hist2d(OMFPDOZ, EHDOZ, cmap=cMap, bins=binsNumZoom, norm=cls.LogNorm())
fig.colorbar(im08,ax=axs[1,2])
axs[1,2].set(xlabel='OMFP differance',ylabel='EH Diff')
axs[1,2].set_xlim(0.0,ZoomBound)
#axs[1,3].set_title('EBS')
#axs[1,3].plot(OMFPD,EBSD,'.b')
_,_,_,im09=axs[1,3].hist2d(OMFPDOZ, EBSDOZ, cmap=cMap, bins=binsNumZoom, norm=cls.LogNorm())
fig.colorbar(im09,ax=axs[1,3])
axs[1,3].set(xlabel='OMFP differance',ylabel='EBS Diff')
axs[1,3].set_xlim(0.0,ZoomBound)
#axs[2,2].set_title('EXC')
#axs[2,2].plot(OMFPD,ExcD,'.c')
_,_,_,im10=axs[2,2].hist2d(OMFPDOZ, ExcDOZ, cmap=cMap, bins=binsNumZoom, norm=cls.LogNorm())
fig.colorbar(im10,ax=axs[2,2])
axs[2,2].set(xlabel='OMFP differance',ylabel='EXC Diff')
axs[2,2].set_xlim(0.0,ZoomBound)
#axs[2,2].set_title('EVXC')
#axs[2,3].plot(OMFPD,EvxcD,'.y')
_,_,_,im11=axs[2,3].hist2d(OMFPDOZ, EvxcDOZ, cmap=cMap, bins=binsNumZoom, norm=cls.LogNorm())
fig.colorbar(im11,ax=axs[2,3])
axs[2,3].set(xlabel='OMFP differance',ylabel='EVXC Diff')
axs[2,3].set_xlim(0.0,ZoomBound)
#axs[3,2].set_title('Eion')
#axs[3,2].plot(OMFPD,EionD,'.m')
_,_,_,im12=axs[3,2].hist2d(OMFPDOZ, EionDOZ, cmap=cMap, bins=binsNumZoom, norm=cls.LogNorm())
fig.colorbar(im12,ax=axs[3,2])
axs[3,2].set(xlabel='OMFP differance',ylabel='Eion Diff')
axs[3,2].set_xlim(0.0,ZoomBound)
#axs[3,3].set_title('Eion')
#axs[3,3].plot(OMFPD,QatD,'.k')
_,_,_,im13=axs[3,3].hist2d(OMFPDOZ, QatDOZ, cmap=cMap, bins=binsNumZoom, norm=cls.LogNorm())
fig.colorbar(im13,ax=axs[3,3])
axs[3,3].set(xlabel='OMFP differance',ylabel='Qat Diff')
axs[3,3].set_xlim(0.0,ZoomBound)
#plt.show()
fig.savefig('zoom_hist_'+args.outPng,dpi=200)
fig.clf()
del fig
print('Have a nice day!')
############HIST2DZOOM################################################################
############NormalZOOM################################################################
fig,axs=plt.subplots(4,4,figsize=(20,20))
fig.tight_layout(pad=5.0)
#axs[0,0].set_title('EBS+EXC-EvXC-EH')
gs=axs[0,0].get_gridspec()
for ax in axs[0,0:2]:
    ax.remove()
axbig = fig.add_subplot(gs[0,0:2])
axbig.plot(ACSFDAZ,EtotDAZ,'or',markersize=msSize)
axbig.set(xlabel='ACSF differance',ylabel='E Diff')
axbig.set_xlim(0.0,ZoomBound)
axbig.set_ylim(0.0,)
#axs[1,0].set_title('EH')
axs[1,0].plot(ACSFDAZ,EHDAZ,'og',markersize=msSize)
axs[1,0].set(xlabel='ACSF differance',ylabel='EH Diff')
axs[1,0].set_xlim(0.0,ZoomBound)
axs[1,0].set_ylim(0.0,)
#axs[1,1].set_title('EBS')
axs[1,1].plot(ACSFDAZ,EBSDAZ,'ob',markersize=msSize)
axs[1,1].set(xlabel='ACSF differance',ylabel='EBS Diff')
axs[1,1].set_xlim(0.0,ZoomBound)
axs[1,1].set_ylim(0.0,)
#axs[2,0].set_title('EXC')
axs[2,0].plot(ACSFDAZ,ExcDAZ,'oc',markersize=msSize)
axs[2,0].set(xlabel='ACSF differance',ylabel='EXC Diff')
axs[2,0].set_xlim(0.0,ZoomBound)
axs[2,0].set_ylim(0.0,)
#axs[2,1].set_title('EVXC')
axs[2,1].plot(ACSFDAZ,EvxcDAZ,'oy',markersize=msSize)
axs[2,1].set(xlabel='ACSF differance',ylabel='EVXC Diff')
axs[2,1].set_xlim(0.0,ZoomBound)
axs[2,1].set_ylim(0.0,)
#axs[3,0].set_title('Eion')
axs[3,0].plot(ACSFDAZ,EionDAZ,'om',markersize=msSize)
axs[3,0].set(xlabel='ACSF differance',ylabel='Eion Diff')
axs[3,0].set_xlim(0.0,ZoomBound)
axs[3,0].set_ylim(0.0,)
#axs[3,1].set_title('Eion')
axs[3,1].plot(ACSFDAZ,QatDAZ,'ok',markersize=msSize)
axs[3,1].set(xlabel='ACSF differance',ylabel='Qat Diff')
axs[3,1].set_xlim(0.0,ZoomBound)
axs[3,1].set_ylim(0.0,)
#axs[0,2].set_title('EBS+EXC-EvXC-EH')
gs=axs[0,2].get_gridspec()
for ax in axs[0,2:]:
    ax.remove()
axbig2 = fig.add_subplot(gs[0,2:])
axbig2.plot(OMFPDOZ,EtotDOZ,'or',markersize=msSize)
axbig2.set(xlabel='OMFP differance',ylabel='E Diff')
axbig2.set_xlim(0.0,ZoomBound)
axbig2.set_ylim(0.0,)
#axs[1,2].set_title('EH')
axs[1,2].plot(OMFPDOZ,EHDOZ,'og',markersize=msSize)
axs[1,2].set(xlabel='OMFP differance',ylabel='EH Diff')
axs[1,2].set_xlim(0.0,ZoomBound)
axs[1,2].set_ylim(0.0,)
#axs[1,3].set_title('EBS')
axs[1,3].plot(OMFPDOZ,EBSDOZ,'ob',markersize=msSize)
axs[1,3].set(xlabel='OMFP differance',ylabel='EBS Diff')
axs[1,3].set_xlim(0.0,ZoomBound)
axs[1,3].set_ylim(0.0,)
#axs[2,2].set_title('EXC')
axs[2,2].plot(OMFPDOZ,ExcDOZ,'oc',markersize=msSize)
axs[2,2].set(xlabel='OMFP differance',ylabel='EXC Diff')
axs[2,2].set_xlim(0.0,ZoomBound)
axs[2,2].set_ylim(0.0,)
#axs[2,2].set_title('EVXC')
axs[2,3].plot(OMFPDOZ,EvxcDOZ,'oy',markersize=msSize)
axs[2,3].set(xlabel='OMFP differance',ylabel='EVXC Diff')
axs[2,3].set_xlim(0.0,ZoomBound)
axs[2,3].set_ylim(0.0,)
#axs[3,2].set_title('Eion')
axs[3,2].plot(OMFPDOZ,EionDOZ,'om',markersize=msSize)
axs[3,2].set(xlabel='OMFP differance',ylabel='Eion Diff')
axs[3,2].set_xlim(0.0,ZoomBound)
axs[3,2].set_ylim(0.0,)
#axs[3,3].set_title('Eion')
axs[3,3].plot(OMFPDOZ,QatDOZ,'ok',markersize=msSize)
axs[3,3].set(xlabel='OMFP differance',ylabel='Qat Diff')
axs[3,3].set_xlim(0.0,ZoomBound)
axs[3,3].set_ylim(0.0,)
#plt.show()
fig.savefig('zoom_norm_'+args.outPng,dpi=200)
fig.clf()
del fig
print('Have a nice day!')
############NormalZOOM################################################################
