#!/bin/sh
#SBATCH --job-name="CY"
#SBATCH --exclusive=user
#SBATCH --ntasks=16
#SBATCH --nodes=1-1
#SBATCH --cpus-per-task=1
#SBATCH --qos=kernph-6hours
#SBATCH --partition=psi
#SBATCH --mem-per-cpu=1600M

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH

